### PR TITLE
Entrypoint.sh now passes along arguments

### LINKED ISSUE #77: Entrypoint does not pass along command line arguments
Command line arguments are sometimes necessary when environment variables cannot be set for the container (e.g. current implementation of Gitlab CI job services). 

Even if there were no such use-cases, command line arguments not being handled is confusing and a feature degradation without a trade-off.

**To reproduce:**
- Create the container:
```bash
docker run -it --rm -p 2113:2113 -p 1113:1113 eventstore/eventstore --run-projections=all --start-standard-projections=true
```

- Browse to http://localhost:2113/web/index.html#/projections

**Expected behavior:**
All system projections should be **Running**.

**Actual behavior:**
All system projections are **Stopped**.

### PR DESCRIPTION
**Pull request by kaancfidan**
Fixes #77

### CODE REVIEW

**Comment by kaancfidan** [comment]
I have uploaded this version of the image to my own docker registry as [kaancfidan/eventstore](https://hub.docker.com/repository/docker/kaancfidan/eventstore).

To see the fix in action, you may:
- Create the container:
```bash
docker run -it --rm -p 2113:2113 -p 1113:1113 kaancfidan/eventstore --run-projections=all --start-standard-projections=true
```

- Browse to http://localhost:2113/web/index.html#/projections

**Expected behavior:**
All system projections should be **Running**.

**Comment by alexeyzimarev** [comment]
@kaancfidan thanks for the PR!

@pgermishuys can you quickly review this? it would also help with adding the `--dev` option

**Comment by bweston92** [comment]
Any update on this?

**Comment by arwinneil** [comment]
Hello,

This pull request has been close due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. 

The pull request has been moved to [EventStore#2655](https://github.com/EventStore/EventStore/pull/2655).

Thank you.

**Pull request closed without merging**
