### PR TITLE
upgrade to 3.8

### PR DESCRIPTION
**Pull request by henry-hz**
upgrade to 3.8
thanks for maintaining this repo :+1:

### CODE REVIEW

**Comment by pgermishuys** [comment]
No worries, thanks for the PR. We should be tagging the Event Store docker images

**Comment by henry-hz** [comment]
I had some issues in building a 3.8 eventstore repo:
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c apt-get update && apt-get install curl -y &&    curl -s https://packagecloud.io/install/repositories/EventStore/EventStore-OSS/script.deb.sh | bash &&    a
pt-get install eventstore-oss=$ES_VERSION -y --force-yes &&    apt-get clean &&    rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/*' returned a non-zero code: 100

**Comment by pgermishuys** [comment]
Let me look into this

**Comment by shouze** [comment]
@henry-hz do the `--force-yes` flag issue is related to docker container?

@pgermishuys has configured tagged releases on docker hub, so everything looks right:

```
docker run --rm -it --entrypoint eventstored  eventstore/eventstore:release-3.8.0 --version
EventStore version 3.8.0.0 (release-ha-v3.8.0/030ef0689d21868b1b83acf59454516bf6db0e53, Tue, 12 Jul 2016 14:40:21 +0200)
```

eventstore-oss has been installed into the container with apt without the `--force-yes` flag, succesfully built [here (you can check the build logs)](https://hub.docker.com/r/eventstore/eventstore/builds/bcefr8uakgkwduqqpv87nkw/)

Can you tell how to reproduce that? Which docker version do you run for the build of the container?

**Comment by henry-hz** [comment]
I downloaded the last one from repo and worked, thanks :+1:

**Pull request merged**
